services:
  - type: web
    name: oral-life-backend
    env: docker
    repo: https://github.com/CrazyAsura/oral-life.git
    rootDir: backend
    plan: free
    envVars:
      - key: PORT
        value: 3001
      - fromContext: MONGODB_URI
        key: MONGODB_URI
